---
galaxy_info:
  author: Heinrich Spreiter
  description: Installs MATE desktop environmet
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
dependencies: []

