---
# tasks file for vnc
- name: Download TigerVNC
  get_url: url={{ vnc_tiger_url }} dest=/tigervnc.tar.gz validate_certs=no

- name: Extract TigerVNC
  unarchive: src=/tigervnc.tar.gz dest=/ copy=no

- name: Clone noVNC
  git: repo={{ vnc_novnc_git }} dest=/usr/local/lib/noVNC accept_hostkey=yes

- name: Install numpy
  apt: name=python-numpy

- name: sym link for novnc launch.sh
  file: src=/usr/local/lib/noVNC/utils/launch.sh dest=/usr/local/bin/novnc.sh state=link

- name: create .vnc folder for default_user_name
  file: path=/home/{{ default_user_name }}/.vnc/ state=directory owner={{ default_user_name }} group={{ default_user_name }}  mode=0755

- name: create vnc passwd
  file: path=/home/{{ default_user_name }}/.vnc/passwd owner={{ default_user_name }} group={{ default_user_name }} state=touch  mode=0600

- name: write vnc server password into vnc passwd
  shell: echo "{{ vnc_server_password }}" | vncpasswd -f > /home/{{ default_user_name }}/.vnc/passwd

- name: copy xstartup
  copy: src=xstartup dest=/home/{{ default_user_name }}/.vnc/xstartup owner={{ default_user_name }} group={{ default_user_name }} mode=0755

- name: copy novnc upstart script
  template: src=novnc.j2.conf dest=/etc/init/novnc.conf mode=0644

- name: copy vncserver upstart script
  template: src=vncserver.j2.conf dest=/etc/init/vncserver.conf mode=0644

- name: reload upstart configuration
  shell: initctl reload-configuration
