---
# tasks file for vnc
- name: Download TigerVNC
  get_url: url={{ vnc_tiger_url }} dest=/tigervnc.tar.gz

- name: Extract TigerVNC
  unarchive: src=/tigervnc.tar.gz dest=/ copy=no

- name: Clone noVNC
  git: repo={{ vnc_novnc_git }} dest=/usr/local/lib

- name: sym link for novnc launch.sh
  file: src=/usr/local/lib/noVNC/utils/launch.sh dest=/usr/local/bin/novnc.sh state=link
