---
galaxy_info:
  author: Heinrich Spreiter
  description: Creates the default user from group_vars/all.yml
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
dependencies: []